name: onkir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_search: ^1.0.0
  flutter:
    sdk: flutter
  get: ^4.3.8
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
